name: Create Test Coverage Badge

on:
  push:
    branches: [ main ]

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  Badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-kotlin@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Kover
        run: ./gradlew koverXmlReport

      - name: Get Coverage Result
        run: |
          {
            echo 'COVERAGE<<EOF'
            (${{github.workspace}}/gradlew --warning-mode none -q printLineCoverage | tail -n1)
            echo EOF
          } >> $GITHUB_ENV

      - name: Update dynamic badge gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{secrets.GIST_SECRET}}
          gistID: ${{secrets.GIST_ID}}
          filename: ${{secrets.GIST_NAME}}
          label: Coverage
          message: ${{env.COVERAGE}}%
          valColorRange: ${{env.COVERAGE}}
          minColorRange: 0
          maxColorRange: 100